apiVersion: ENC[AES256_GCM,data:fM8=,iv:XF30DjtgKSnrW+OlQrYqGKcJl/TyVfG5anoav2mkIhw=,tag:k8FIRVktUQVCjd1FrfyPbg==,type:str]
data:
    dsc2saltkey: ENC[AES256_GCM,data:T+oLsxllJKA3lC2+,iv:yGrHEVdyyVKdstTJfZyei4b3XYP42vNRvNF/WCr1iqY=,tag:OtrYyG/gM4v1MmeKg/gMtQ==,type:str]
kind: ENC[AES256_GCM,data:+ejmBV15,iv:lMBah+e3L4qUTm0REaVI5U1PlzxclQsrZ+lYlNOkhDU=,tag:T/qXrRJPZFv8vxPpOsauhw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0IjMCc6yRjWB6Q==,iv:X4ONKZkUgW0Q/eJ8fiv/pO0+ESGH0jRLCizs/hE1Glc=,tag:BvX41jdE7h+hOXAP0UParA==,type:str]
    namespace: ENC[AES256_GCM,data:u/4zwZwahA==,iv:oXgtzwAbH9bpLybuOpHUkYzyJI+MCvN+9bxNtPp2LSk=,tag:T3BldmkqxzPPshFW5wd/lA==,type:str]
type: ENC[AES256_GCM,data:ecjUEEhg,iv:mmFekNKzmFgi8YVhPmtdKjKaZUJMK2BxpvGiKoxDtkE=,tag:XKHntq2xDbc2aIOQIQ5aeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3akRMUExreWkvUlNKQ1ZC
            Mm1Db3ZIWDVMYTQ5VzV1bXRZUjdJaHd2QVFzCk5tazY1UTQyZE9xVjNUYUdjZlVN
            eURYYzBWNEpKUy9wVlJTNkw0Qjg4MncKLS0tIEFvVUJkeGNvUlZkUGFIeVZDR0Z0
            dkhQbmhhTGc4NTBrR1lnOVBFZXZtdWcK9iDodGxjzgk7TIqNN1nCVMP7dipWA6RA
            QqM+W9ArO/3CswEBUf+sdLvg9HT1XRvnU2c264/WFIK3M22YCnz3tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T17:12:27Z"
    mac: ENC[AES256_GCM,data:1XFnsRRv+MJmajN3iwrk4A9hNL9BUQxz+sCOHrrY4YanwhjyAf7FDFA9QfkZUC3eu3hcblsH8rWnVa7IVvsaXWF1WY/YiylUU2VunlEpRxTrbdcex4075ZgH5QYf7Vzr3kvtHlO5RtV0oPYDwpJ66XquJvh/Gm0A+1lyW+E8+Wc=,iv:J8d1Qp89OyZGyFzKFm9OPx4eqJyZhbxc+hQPQy/X4/4=,tag:IDqqcZFHkIqpWDVWZTCQtQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
