apiVersion: ENC[AES256_GCM,data:l+M=,iv:HBTsCKbx65LWkEeTy9NEkv6ZDj0AVMNVx8u4d/QGfwE=,tag:wpPop44c2WLGZJqWKuMc6Q==,type:str]
kind: ENC[AES256_GCM,data:paUP+cc3,iv:lNDHScKdmDgIMOA09uuUPVaSBvp6enjMn6o12iwDv+Y=,tag:KPEAv61iL+866a0mofQlGA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Tz3ccPH9k8e288d6sws=,iv:IfY9BCyar5KjvVN/bvnIkJ8fPkgi6Oykt5bbcT/1BsM=,tag:AyQoDpvrK0tFWfFGyUEgxw==,type:str]
    namespace: ENC[AES256_GCM,data:I5cD13SmowTGzdc=,iv:UZoq40V2wa518gJkD0CZx4cGSivzrR5qG42sFl0EZDo=,tag:St3D0vFF3LWi5l6JStcTPw==,type:str]
type: ENC[AES256_GCM,data:oWufaP0fR0jeDG4tTB7LyLq+dd3eY8x7Jkdx4s96,iv:fPmVRkkPArqahTS4IG6N6WGV+3cHCLtaMpJZnvcJR80=,tag:v7Uypzw+SnhguoO+B4lkGw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:xCGPD8EymmcCeiEXnSTUUqDZWf2pWhKu7AxVbdZaTFyaFaH4Gsc4eU3pfK/RVd49bI8lsTzBCJvnQuOoe3fXKly9gKE/Q+FPEsMJcKDU8or59CYTPsMzPCXl4TEHWgos3JjWBiZa29/2P6UFiclsDAVfsJnW1kDH7cUef9CuLX2TcOCEevIB1JhGJWIr07bfDCe5gR+AqGpvPKy3BpqPZ/w4nE0KOTTgMwtiGmWW7jWRLbi7hpQrz94K8azF6Ui02iRECH3fI/2Op2eG,iv:q+o5x9doEru3RT2FnZWEBUsfJFQvxxEXQcirkSfNtbI=,tag:5bu5DyMkK8lPi7/u1wPStg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcnZOZTBQdWd6NDJnNUtN
            YU0wYzVFTW9ReHNoWHRpR3h0WHZ3UndZQ1c0CjdST00zQWpGK1FLK1kyWnV5aytl
            bjlwNSt5UmVZU2hwVkJuZkY4MW9IYUUKLS0tIGdFWXJoRmd0U2lQNEdTTEQwYXdx
            NUs2K244ZFppeGZGSFN1TldjOGpCNEkKplkwvybIkxWD+FjN42HSp6PZiGM/Qvua
            t1DIyVVzNEIhHjtzKVg5w54xx45ayYt4Wi3UP9guXOOtmdLhGJg40w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T15:33:33Z"
    mac: ENC[AES256_GCM,data:LtpM+f88pQ8A8dVZn2Vpy4fDgeLrwhskhj0GwSol5jSLG4djAn26XDo7esohh55c7RArsysKKSLuglZb/lbBrl5nguwVSc1PnQphOnGsbahapBuNEMDpy9lIsUvXhk4NMrLowJt6WT7cOjbVANLhfmA69iCp6O7Q/3CWNMtuCS8=,iv:bO4nR3ghMpw0pJphkfhegqwBZdDqjn2UQrKiK85dpro=,tag:QHj1TZ/YbsKHuQCADruWZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
