apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: customer-record-route-config
  namespace: default
spec:
  service:
    name: customer-record
  routes:
  - predicates:
    - Path=/customer-record/**
    filters:
    - StripPrefix=1
    - PrefixPath=/