apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tj17
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tj17
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  env:
  - name: fooval
    valueFrom: 
      secretKeyRef:
        name: my-secret
        key: fooval
  #- name: logging.level.root
  #  value: DEBUG
  - name: test.var
    value: testvalue
  - name: dsc2.salt
    valueFrom:
      secretKeyRef:
        name: my-secret2
        key: dsc2saltkey
  - name: JAVA_TOOL_OPTIONS
    value: "-Ddsc.salt=dscvalue"
    #valueFrom:
    #  secretKeyRef:
    #    name: my-secret3
    #    key: dscsaltkey
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/tfynes-pivotal/tj17
      ref:
        branch: main
